name: Go CI/CD Pipeline

on:
  push:
    branches:
      - master # Trigger this workflow on push to the main branch
  pull_request:
    branches:
      - master # Trigger this workflow on PR to the main branch

jobs:
  go:
    runs-on: ubuntu-latest # Using an Ubuntu runner for the pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the code from the repository

      - name: Set up Go
        uses: actions/setup-go@v3 # Set up the Go environment
        with:
          go-version: "1.24.2" # Set the Go version you want to use (adjust if necessary)

      - name: Cache Go modules
        uses: actions/cache@v3 # Cache Go modules to speed up build
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod tidy # Ensure Go dependencies are up to date

      - name: Run GoLint
        run: go run golang.org/x/lint/golint ../.. # Run GoLint to check for code style issues

      - name: Run GoTest
        run: go test -v ../.. # Run Go unit tests
